### ISSUE TITLE
공공 데이터 포털 리서치 (데이터)

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_6_dataanalysis#14]
공공 데이터 포털 리서치 (데이터 )
- 지역 화폐 검색했을 때 활용할 수 있는 데이터 분류하고, 어떤 데이터 있는지 리스트업 필요

**Comment by Datajs1** [comment]
**[데이터 리스트업]**
1. 가맹점 현황
- 시군명, 상호명, 업종명, 정제도로명주소, 정제지번주소, 정제우편번호, 정제위도, 정제경도, 사업자등록번호, 업종코드, 가맹점번호, 휴폐업상태, 휴폐업상태코드, 폐업일자
2. 발행 및 이용현황
- 시군코드, 시군명, 기준년월, 월별신규가입자수(명), 월별충전액(백만원), 월별사용액(백만원)
3. 업종별 건수 및 금액
-  카테고리별, 결제건수, 결제금액
4. 업종별 결제정보
- 기준년월, 시군구명, 읍면동명, 성별, 연령대, 업종명, 결제건수, 결제건수, 결제금액, 데이터기준일
5. 기간별 이용금액
6. 발급월별 소비금액
- 발급년, 발급월, 광역시도코드, 광역시도명, 시군구코드, 시군구명, 법정동코드, 법정동명, 연령대, 성별, 지수_이용건수, 지수_이용금액
7. 지역화폐 결제 내역
- 결제날짜, 업종, 결제건수, 결제금액, 데이터기준일자
8. 연령별 이용현황
9. 성별별 이용현황
- 기준연도, 시군명, 연령대, 성별, 결제건수, 결제금액, 결제취소건수, 결제취소금액, 1회평균결제금액
10. 매출 유출지 집계
- 유출지행정코드, 매출금액, 매출금액_순위, 매출금액비율, 전월대비 증감값, 전월대비증감비율, 전년동월대비증감율, 전년동월대비증감율
11. 분석시스템 지역화폐매출 유입지 집계
12. 지역화폐수요분석
- 기준년월, 성별코드, 연령대코드, 시도명, 시군구명, 행정동명, 업체형태명, 기업설립년월, 업종코드, 업종대분류명, 보증금액, 보증일자, 대위변제금액, 부실발생일자, 가맹점 정보, 폐업일자, 지역화폐사용년월, 정책카드결제금액, 정책카드결제수, 일반카드결제금액, 일반카드결제수, 기업번호
13. 전통시장별 지역화폐 거래 데이터(부산만)
- 기준일자, 기준시간대값, 전통시장명, 전통시장주소, 카드사명, 업종코드, 업종명, 출생년도, 성별코드, 거래건수, 총거래금액
14. 행정동 단위 업종별 지역화폐 거래 데이터(부산만)
- 기준일자, 기준시간대값, 전통시장명, 전통시장주소, 카드사명, 업종코드, 업종명, 출생년도, 성별코드, 거래건수, 총거래금액


**이슈**
- 전국 데이터가 아닌 일부 지역만 제공해주는 데이터 형태가 대부분(가맹점 현황 예외)
- 주기적 업데이트가 되지 않음

**Comment by syleeie2310** [comment]
- 데이터의 메타 데이터를 정리해야 됨
- 메타 데이터는 포맷을 맞췄으면 좋겠음
- 지역마다 다를 수 있기 때문에, 데이터 파일명까지 분류해야 될 수 있음
- 종합 > 메타 데이터부터 정리해보기
(가맹점 현황 -> 지역 별로 네이밍 정리해보기)

**Comment by syleeie2310** [comment]
데이터 유형
- CSV, Excel, Text, Json 그외의 HTML, XML 포맷이면 어떻게 정리해야될지 데이터 포맷도 메타 데이터에 표시해야 될듯

**Comment by syleeie2310** [comment]
공공데이터포털 구글 시트 -> 메타 데이터

**Comment by Datajs1** [comment]
[공공데이터포털_METADATA_F.xlsx](https://github.com/user-attachments/files/17866974/_METADATA_F.xlsx)

주제별 / 지역별 구분

**Comment by syleeie2310** [comment]
- 파일명에 날짜로 끝나는 경우가 어떤 의미인지?
- 지역화폐가맹점 -> 데이터 목록 팝업 (메타 데이터)
- 분류 체계
-> 대, 중, 소 (-)

- 지역별로 구성되어 있는 지역화폐가맹점 vs 전국 지역화폐가맹점 데이터 차이가 없으면 오른쪽 사용하면 될듯
- 사용 가능한 종류 데이터 ---> 경기도

**Comment by syleeie2310** [comment]
메타 데이터 델타 테이블 구성한 다음에 종료

**Comment by Datajs1** [comment]
- 파일명에 날짜로 끝나는 경우가 어떤 의미인지?
A. 데이터 수집 날짜
- 등록일과 차이나는 이유는?
A. 데이터 등록 심의가 있어서 수집일과 등록일 차이

**Comment by syleeie2310** [comment]
1.분류 체계 -> 대, 중
2.파일명에 날짜로 끝나는 경우가 어떤 의미인지? -> 데이터 수집 날짜
3.지역별로 구성되어 있는 지역화폐가맹점 vs 전국 지역화폐가맹점 (조폐) 차이 

1) 지역 128개 CSV 합치는 것 -> 테이블
2) 전국 지역화폐가맹점 (조폐공사) -> API 데이터

4. 델타 테이블
-> created_at (데이터 생성 시점), updated_at (데이터 변경 시점) (timestamp(kst))

**Comment by Datajs1** [comment]
공공데이터 파일 업로드 완료
경로 : bronze.file_public

파일명 : daejeon_localcurrency_publication_usage_01_241128
> raw 파일 영어로 변환+데이터업로드 날짜
