### ISSUE TITLE
소상공인시장진흥공단(상가, 상권 정보) 데이터 확보 및 리서치

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_6_dataanalysis#15]
소상공인시장진흥공단(상가, 상권 정보) 
---> 사장님이 어떤 지역화폐 운영하는지?, 그외의 것은 지은님이 추가로 조사 필요

**Comment by jjjjjeeeeew** [comment]
1) 소상공인시장진흥공단 상가 및 상권 정보(240930 기준)
https://drive.google.com/file/d/14Um5f1cgToU6CPNG3OdpA6Lc-3A4ft4X/view?usp=drive_link

2) 전국 지역화폐 가맹점 표준데이터(241108 기준)
[전국지역화폐가맹점표준데이터-20241118.xls]
(https://github.com/user-attachments/files/17823288/-20241118.xls)

3) 상권정보시스템(https://sg.sbiz.or.kr/godo/index.sg)
행정구역별 업소수, 유동인구, 매출, 직장인구, 주거인구, 소득·소비, 세대 수 정보 제공
행정구역별 업종분석, 매출분석, 인구분석, 지역현황 정보 제공

4) 개인 사업자 매출 및 지역화폐 매출 현황_경기**유료데이터(1,243,000원)
(https://bigdata-region.kr/#/dataset/7ee8c8d3-dbed-48f2-8980-31db8e64e86f)
기준년월/시도명/시군구명....업종대분류코드/총기업수/총매출금액/지역화폐사용수/지역화폐총사용액

**Comment by syleeie2310** [comment]
1. 소상공인시장진흥공단 상가 및 상권 정보(240930 기준)
-> 메타 데이터 정리 필요

2. 전국 지역화폐 가맹점 표준데이터(241108 기준)
-> 메타 데이터 정리 필요 -> 공공데이터포털 > 정보공유 > 자료실 (설명)

3. 상권정보시스템(https://sg.sbiz.or.kr/godo/index.sg)
- 레퍼런스, 데이터는 아니다.

4. 개인 사업자 매출 및 지역화폐 매출 현황
- 유료 패스

**Comment by jjjjjeeeeew** [comment]
1. 메타데이터정리 https://docs.google.com/spreadsheets/d/1HiCVC-4dK3jZYny0BIG142vR4QK_I7b2/edit?usp=drive_link&ouid=115876357194241640531&rtpof=true&sd=true

**Comment by syleeie2310** [comment]
해당 메타 데이터는 진섭님 데이터로 추가해서 합치기

**Comment by jjjjjeeeeew** [comment]
[메타데이터 추가 완료]
https://docs.google.com/spreadsheets/d/1l5zUdRQYW1eD6HywHR55KpwHfQw2aXMy/edit?usp=drive_link&ouid=115876357194241640531&rtpof=true&sd=true
