### ISSUE TITLE
경기데이터드림 오픈 API 개발

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_6_dataanalysis#16]
지역화폐 활용할 수 있는 데이터 중에 OpenAPI 선정하여 데이터브릭스에서 개발
- 윤진섭님과 이야기 필요 (공공 데이터 포털에 있는 것 중에 1개 선정)

**Comment by syleeie2310** [comment]
- 데이터브릭스 노트북 관리 필요 ---> 브런치 만들어서 작업할 것
- perpage 1천개식 작업 (6백5십만개)

**Comment by syleeie2310** [comment]
지역화폐 API 리스트 파악 해서 구글 시트로 정리 필요

**Comment by seongun-kang** [comment]
https://docs.google.com/spreadsheets/d/1OrspJdUM3IXuUf8PqAE_jvwAB8omSH46/edit?usp=drive_link&ouid=104317592448484294127&rtpof=true&sd=true

**Comment by syleeie2310** [comment]
- 실패했을 때 다음 요청을 받아서 하면 되고, 델타 테이블로 append -> 스키마 레벨 결정 필요 (bronze_api)

**Comment by syleeie2310** [comment]
- api 리스트 (경기데이터드림, 공공데이터포털 --> 소스)
- 한국조폐공사 데이터는 최근 데이터 존재 확인 -> 대부분 1회성 수집하면 될듯
- 수집기에서는 로직을 크게 두지 않는 것으로 개발

**Comment by seongun-kang** [comment]
지은님하고 스키마 얘기해서 브론즈 스키마 정리
카탈로그랑 스키마 구축, 델타레이크 저장 후 스키마까지 저장하는거 해봐야함
슬랙 워크플로우 웹훅 연동 -완-
api 사용하는 포털 정리 후 키 발급 및 시크릿 키 설정, 팀원들에게 권한 부여
구글드라이브 api 연동 -미완-

**Comment by seongun-kang** [comment]
테스트

**Comment by seongun-kang** [comment]
test

**Comment by seongun-kang** [comment]
![image](https://github.com/user-attachments/assets/0097982b-5896-4eed-8c25-faa12202dbb0)
워크플로우까지 완료했습니다
