### ISSUE TITLE
소상공인연합회, 경기신용보증재단, 더아이엠씨, 지방재정경제실 데이터 리서치

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_6_dataanalysis#18]
소상공인연합회, 경기신용보증재단, 더아이엠씨, 지방재정경제실 데이터 리서치
- 확보 가능한 데이터 확인

**Comment by chae010** [comment]
1.
[행정안전부 내고장알리미]
- 전국 지역 사랑 상품권에 대한 정보를 볼 수 있는 사이트 url 모음. 
- https://www.laiis.go.kr/lips/mlo/lcl/localGiftList.do

2.
[공공데이터에서 쓰이는 지역코드 구도]
[localcode.csv](https://github.com/user-attachments/files/17825486/localcode.csv)
결과코드	resultCode	
결과메시지	resultMsg
한 페이지 결과 수	numOfRows	
페이지 번호	pageNo
전체 결과 수	totalCount	
수신 문서양식	type	
지역코드	region_cd	
시도코드	sido_cd	
시군구코드	sgg_cd	
읍면동코드	umd_cd	
리코드	ri_cd	2	
지역코드_주민	locatjumin_cd	
지역코드_지적	locatjijuk_cd	
지역주소명	locatadd_nm	
서열	locat_order	
비고	locat_rm	
상위지역코드	locathigh_cd		
최하위지역명	locallow_nm	
생성일	adpt_de

 3.
[서울 지역사랑상품권 지수]
[서울시 지역사랑상품권 지수.csv](https://github.com/user-attachments/files/17825493/default.csv)
SCTN_NO	구분번호	
SIGNGU_NM	시군구명	
SIGNGU_CD	시군구코드
INDUTY_CD	업종코드	
INDUTY_NM	업종명	
QU_CNT_SUM	분기건수합계
QU_AMT_SUM	분기금액합계	
CRTR_YR	기준년도	
CRTR_YR_QTR	기준년분기
DATA_LOAD_DT	데이터로드일자	

4.
[조폐공사 데이터]
전통시장 역세권
한국조폐공사_지역사랑상품권_결제정보
한국조폐공사_지역사랑상품권_운영정보
한국조폐공사_지류_지역사랑상품권_지점별_재고정보
한국조폐공사_지류_지역사랑상품권_판매지점정보
한국조폐공사_지역사랑상품권_지자체별_판매정책정보
한국조폐공사_지류_지역사랑상품권_환전지점정보
한국조폐공사_카드_가맹점기본정보
한국조폐공사_모바일_가맹점기본정보
한국조폐공사_지류_가맹점기본정보
한국조폐공사_통합_가맹점기본정보
행정안전부_통계연보_지역사랑상품권

**Comment by syleeie2310** [comment]
[행정안전부 내고장알리미]
-  지방재정경제실 데이터 리서치 -> 손 수집 가능 -> 포맷만 잘 설정하셔서 데이터브릭스에서 가져갈 거 생각해서 정리 부탁드립니다.

[더 아이엠씨]
- 화폐 사용량 : 경기지역경제포털, 경지역화폐의 결제금액, 정보, 지역화폐 사용빈도 현황, 행정안전부 음식점 업소정보, 국가통계포털 국내통계

[공공데이터에서 쓰이는 지역코드 구도]
- 행안부 [행정기관(행정동) 및 관할구역(법정동) 변경내역(2024.8.1. 시행)](https://www.mois.go.kr/frt/bbs/type001/commonSelectBoardList.do?bbsId=BBSMSTR_000000000052) 
- https://www.code.go.kr/stdcode/regCodeL.do

**Comment by syleeie2310** [comment]
[서울 지역사랑상품권 지수]
- 메타 데이터 정리. 

[업종 참고]
https://kostat.go.kr/board.es?mid=a10403040000&bid=107&act=view&list_no=428660

**Comment by syleeie2310** [comment]
다른 소스로 가져올 수 있는 지역화폐가 더 없는지? 토요일까지 정리 부탁드립니다.

**Comment by chae010** [comment]
1. 손수집 
https://docs.google.com/spreadsheets/d/1d2p6VPuBJIMHHbIbyb4ePo309YwB20TF/edit?gid=1408292766#gid=1408292766
2. 더아이엠씨 리퍼런스 조사
https://docs.google.com/spreadsheets/d/1IIi2NWEVMP8d2iG6fFKTkYp-hf2MtPg-gpzJx-Jjx-A/edit?gid=0#gid=0
3. 국가통계포털 KOSIS
https://kosis.kr/index/index.do#none  
검색어 : 지역화폐 , 지역상품권

**Comment by syleeie2310** [comment]
[행정안전부 내고장알리미]
-> 11/23(일) 최신 버전으로 지역 별로 지역화폐 상품권 별로 메타 데이터 테이블
-> 델타 테이블 2개 (서울 , 그외) 데이터 올리고 구축하기
-> 할인율이 매달 변경됨 ---> 본인이 분석하기 좋은 데이터 포맷이 고민해보면 좋을 듯

[더아이엠씨 리퍼런스 조사]
-> 전국사업체조사 : 사업체 관련된 것
-> 가맹졍 별 결제정보 : 파일데이터명 ---> 코나아이 ---> 가격 문의해봐도 됨
-> 4개 테이블 분리해서 메타 데이터 포맷 정리.

[기타 수집]
-> 국가 통계포털 : 지역화폐 검색했을 때 통계표 --> 가이드 (지역화폐 개선사항, 지역화폐 결제방법, 지역화폐 이용하지 않는 이유) -> 통계표
(리스트를 메타 데이터로 정리 필요 ---> 화요일까지)
-> 서울페이 : 서울시 서울사랑상품권 ---> 메타 데이터 정리 (서울페이앱분류업종-자치구-상품권매출금액-매출건수)

**Comment by chae010** [comment]
https://docs.google.com/spreadsheets/d/1IIi2NWEVMP8d2iG6fFKTkYp-hf2MtPg-gpzJx-Jjx-A/edit?gid=51059206#gid=51059206

**Comment by syleeie2310** [comment]
국가 통계포털 ---> 통계표 데이터 CSV로 내려야할지? APIㄹ 개발해야될지 결정 필요 (목요일까지)

**Comment by chae010** [comment]
https://docs.google.com/spreadsheets/d/1IIi2NWEVMP8d2iG6fFKTkYp-hf2MtPg-gpzJx-Jjx-A/edit?gid=51059206#gid=51059206

**Comment by syleeie2310** [comment]
kosis_meta 업로드

**Comment by syleeie2310** [comment]
@chae010 
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/3eaa4e07-312c-42b8-8b38-08e73d3b8ffb">

보니깐 파일이 애초부터 깨져있는거 같은데, 저 메타 데이터 export 할때 어디서 하셨어요? 구글 드라이브 인가요??

처음에 내보낼 때 encoding이 깨진듯 해서, 그쪽부터 먼저 보는게 좋을 듯 합니다.

혹시 안되면 ui 통해서 업로드 하세요~

**Comment by syleeie2310** [comment]
확인 완료!
