### ISSUE TITLE
카탈로그(브론즈/실버/골드) 스키마 체계 잡기

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_6_dataanalysis#20]
카탈로그(브론즈/실버/골드) 스키마 체계 잡기

---> 초안만 토요일까지 이야기 해봅시다.

스키마
---> 전국, 경기, 지역??
---> 데이터 유형에 따라 스키마를 나누면 좋을지??

구글 드라이브 데이터 폴더 기준 ---> 데이터브릭스로 옮길거라서

**Comment by jjjjjeeeeew** [comment]
[1안]
https://docs.google.com/spreadsheets/d/1bqbUoxgtV7Gzld3f_Vj7dOvJjXm0-6iv/edit?usp=drive_link&ouid=115876357194241640531&rtpof=true&sd=true

**Comment by jjjjjeeeeew** [comment]
https://docs.google.com/spreadsheets/d/1IqYF_YZ0knr3OFxTNfwon7nM-6DusKC1VwwrbzwGyWM/edit?usp=drive_link

**Comment by jjjjjeeeeew** [comment]
진섭님과 csv 파일로 일부 업로드 완료(API 개발로 전체 테이블 구성할지, 다운로드완료한 csv 파일 형태로 테이블 구성할지 논의 진행중)

**Comment by syleeie2310** [comment]
소스-항목-데이터 형태? ---> 테이블

카탈로그 오전에 이야기 해보고 확정해서 slack한테 태그 걸고 말씀해주세요~

**Comment by jjjjjeeeeew** [comment]
[카탈로그-스키마 체계 확정 완료]
![bronze](https://github.com/user-attachments/assets/1e281ac9-3887-4401-b2dd-5010d17c5d36)

**Comment by syleeie2310** [comment]
고생하셨습니다~ 완료 처리 해주세요
