### ISSUE TITLE
브론즈 데이터 업로드

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_6_dataanalysis#29]
브론즈 데이터 업로드
-> 공공데이터포털 : 진섭님, 이지은님
-> kosis, 통계청 ; 채현님

**Comment by syleeie2310** [comment]
**- 메타 데이터 포맷**
-> https://docs.go**ogle.com/spreadsheets/d/1iB0oVv0Us-nktuG8KQedu7qQys5ALxiX/edit?gid=511566663#gid=511566663

**- 공공 데이터 포털**
-> api까지 개발 가능 (공공데이터포털)

**Comment by jjjjjeeeeew** [comment]
https://tacademykr-dataanalysis.cloud.databricks.com/editor/notebooks/3802697883722016?o=2766527531974171

**Comment by syleeie2310** [comment]
테이블(메타) 
- bronze.meta_public.public_meta_241128

**Comment by jjjjjeeeeew** [comment]
- 공공데이터포털 전국지역화폐가맹점표준데이터 -> API 개발 완료되어 file 데이터는 업로드 진행 취소
- KOSIS '지역화폐' 키워드 데이터 데이터브릭스 델타테이블 업로드 완료

**Comment by syleeie2310** [comment]
완료 처리해주세요~
