### ISSUE TITLE
KOSIC 기초통계 파악

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_6_dataanalysis#30]
KOSIC 데이터 현황 파악 ---> 화요일까지 기초통계 정리해주세요.

**Comment by syleeie2310** [comment]
- 테이블 별로 데이터 건수
-> 테이블 스키마 -> 기초통계
( 숫자 summary (통계량),  카테고리 건수, 시계열 그래프 )

**Comment by chae010** [comment]
https://www.notion.so/_1o-Clock-1404ac89ef028054a70cf1903cb53654

**Comment by syleeie2310** [comment]
unpivot 잘 구성해서 대시보드에서 어떻게 보여주면 좋을지 - depth 1~3

**Comment by syleeie2310** [comment]
- unpivot 속성별로 테이블 구성 완료

**Comment by syleeie2310** [comment]
- https://docs.databricks.com/en/notebooks/widgets.html

**Comment by syleeie2310** [comment]
- https://docs.databricks.com/en/dashboards/index.html
