### ISSUE TITLE
법정동 코드/표준산업분류 코드 값

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_6_dataanalysis#38]
표준산업분류 코드 마스터
https://upjong.co.kr/industry-code-standard-industry-classification-link-table/
https://www.nts.go.kr/comm/nttFileDownload.do?fileKey=dc054e55089b8d6d8679797c686aff63

법정동/행정동 코드 마스터
...

**Comment by syleeie2310** [comment]
법정동/행정동 코드 마스터 테이블 아래 볼륨에다가 업데이트 했습니다. 작업하실 분은 토요일에 말씀드릴게요
- https://tacademykr-dataanalysis.cloud.databricks.com/explore/data/volumes/bronze/etc/metadata?o=2766527531974171
- 아래 데이터 기준
- https://www.mois.go.kr/frt/bbs/type001/commonSelectBoardList.do?bbsId=BBSMSTR_000000000052

[참고]
https://www.code.go.kr/stdcode/regCodeL.do

**Comment by syleeie2310** [comment]
meta_master_kikcd_h
<img width="557" alt="image" src="https://github.com/user-attachments/assets/300b9fd8-68bd-42ee-8f96-1b704c881124">

meta_master_kikcd_b
<img width="599" alt="image" src="https://github.com/user-attachments/assets/9095e393-b2c7-486b-920e-da27d911d58a">

meta_master_kikmix
<img width="518" alt="image" src="https://github.com/user-attachments/assets/edb673bb-484d-49d2-b8bb-08f2b5818ded">

**Comment by seongun-kang** [comment]
![image](https://github.com/user-attachments/assets/7c6efeee-df8b-439d-b435-0ec6289ca03c)
Unity Catalog 환경에서는 dbfs:/ 스키마를 사용하는 테이블 생성을 지원하지 않는다고 Unity Catalog에서 테이블을 생성하려면 Unity Catalog와 호환되는 볼륨 또는 카탈로그를 설정해야 한다고합니다!
옵션 1: Unity Catalog를 설정하고 사용
-> 이 방법으로 진행할 경우 aws s3의 Access Key ID와 Secret Access Key가 필요하다고합니다.
옵션 2: Unity Catalog를 우회하고 기존 방식 사용
->  이 방법으로 진행할 경우, Unity Catalog를 사용하지 않고 Databricks File System(DBFS)을 통해 작업을 진행해서 테이블 등록 없이 Delta 포맷으로 데이터를 저장하며, 필요할 때 Delta 테이블을 로드해서 작업을 수행할 수 있다고합니다.

어떤 방법으로 진행해야하나요?

**Comment by syleeie2310** [comment]
@seongun-kang 저장할때 path를 managed location으로 설정해주시면 됩니다. 테이블 location은 
aws s3의 Access Key ID와 Secret Access Key 필요하다는건 그중의 하나 방법이지, 꼭 없어도 되요, 기존에도 왼쪽 key 없이도 테이블 만드셨으니깐..

DBFS에 읽거나 쓰는게 저번에도 이야기 드렷듯이 권장하는 방법이 아니에요. 읽을 때엔 volumn 기능을 쓰시고 데이터 위치를 지정하지 말고 managed location을 쓰시면 되고,  managed location은 생성한 스키마랑 동일합니다. (externel location이 아닌 managed location은 스키마를 쫓아갑니다.)

고로 dbfs로 지정하지 말고 테이블명만 입력하면 됩니다.

진행하다가 막히면 다시 말씀해주세요. 그리고 documentation 을 꼼꼼히 읽으셔야 되요.

**Comment by seongun-kang** [comment]
@syleeie2310 넵 알려주셔서 감사합니다 시도해보고 막히면 질문하겠습니다!
