### ISSUE TITLE
API 참고문서 데이터 / 코드 메타 테이블 구성 필요

### ISSUE THREAD

**Issue by syleeie2310** [da-analysis/asac_6_dataanalysis#39]
API 참고문서 데이터 / 코드 메타 테이블 구성 필요

**Comment by seongun-kang** [comment]
https://docs.google.com/spreadsheets/d/1f31Nfu4ld-Q_dUVjZSXJv_JUbZhJc_ZcUafqlbc5YMU/edit?usp=drive_link

**Comment by seongun-kang** [comment]
![image](https://github.com/user-attachments/assets/c490e9a1-446a-4087-8691-6ac25cb6d6a6)
